-- Esquema final verificado; ejecutar en una base vacía.
BEGIN;
SET LOCAL search_path = public, pg_catalog;

CREATE TABLE public."Roles" (
    "Id" integer NOT NULL,
    "Name" varchar(100) NOT NULL
);

CREATE TABLE public."Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Username" varchar(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Name" varchar(200) NOT NULL,
    "RoleId" integer DEFAULT 2 NOT NULL,
    "IsActive" smallint DEFAULT 1 NOT NULL
);

CREATE TABLE public."Branches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" varchar(200) NOT NULL,
    "Address" varchar(500) NOT NULL
);

CREATE TABLE public."Tickets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "BranchId" integer NOT NULL,
    "TechnicianId" integer NULL,
    "Title" varchar(200) NOT NULL,
    "Description" text NOT NULL,
    "Status" varchar(20) NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "UpdatedAt" timestamptz NOT NULL,
    "ScheduledAt" timestamptz NULL,
    "ClientRequestId" uuid NULL,
    "ReporterUserId" integer NULL
);

CREATE TABLE public."CoordinatorTechnicians" (
    "CoordinatorUserId" integer NOT NULL,
    "TechnicianUserId" integer NOT NULL,
    "CreatedAt" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public."Evidences" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TicketId" integer NOT NULL,
    "Description" text NOT NULL,
    "PhotoPath" text NULL,
    "CreatedAt" timestamptz NOT NULL,
    "PhotoBase64" text NULL
);

CREATE TABLE public."TicketEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TicketId" integer NOT NULL,
    "EventType" varchar(32) NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "UserId" integer NOT NULL,
    "ClientRequestId" uuid NOT NULL,
    "PreviousScheduledAt" timestamptz NULL,
    "ScheduledAt" timestamptz NULL,
    "EvidenceId" integer NULL
);

CREATE TABLE public."TicketStatusRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TicketId" integer NOT NULL,
    "RequesterUserId" integer NOT NULL,
    "Type" varchar(32) NOT NULL,
    "Reason" text NULL,
    "Status" varchar(20) DEFAULT 'PENDIENTE'::character varying NOT NULL,
    "CreatedAt" timestamptz NOT NULL,
    "ReviewedByUserId" integer NULL,
    "ReviewedAt" timestamptz NULL,
    "ClientRequestId" uuid NOT NULL
);

ALTER TABLE public."Branches" ADD CONSTRAINT "Branches_pkey" PRIMARY KEY ("Id");
ALTER TABLE public."CoordinatorTechnicians" ADD CONSTRAINT "CoordinatorTechnicians_pkey" PRIMARY KEY ("CoordinatorUserId", "TechnicianUserId");
ALTER TABLE public."Evidences" ADD CONSTRAINT "Evidences_pkey" PRIMARY KEY ("Id");
ALTER TABLE public."Roles" ADD CONSTRAINT "Roles_pkey" PRIMARY KEY ("Id");
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "TicketEvents_pkey" PRIMARY KEY ("Id");
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "TicketStatusRequests_pkey" PRIMARY KEY ("Id");
ALTER TABLE public."Tickets" ADD CONSTRAINT "Tickets_pkey" PRIMARY KEY ("Id");
ALTER TABLE public."Users" ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("Id");
ALTER TABLE public."Evidences" ADD CONSTRAINT "UQ_Evidences_TicketId_Id" UNIQUE ("TicketId", "Id");
ALTER TABLE public."Roles" ADD CONSTRAINT "UQ_Roles_Name" UNIQUE ("Name");
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "UQ_TicketEvents_UserId_ClientRequestId" UNIQUE ("UserId", "ClientRequestId");
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "UQ_TicketStatusRequests_ClientRequestId" UNIQUE ("ClientRequestId");
ALTER TABLE public."Tickets" ADD CONSTRAINT "UQ_Tickets_ClientRequestId" UNIQUE ("ClientRequestId");
ALTER TABLE public."Users" ADD CONSTRAINT "UQ_Users_Username" UNIQUE ("Username");
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "CK_TicketEvents_Description" CHECK ( length(btrim("Description")) > 0 OR ("EventType" = 'SEGUIMIENTO' AND "EvidenceId" IS NOT NULL));
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "CK_TicketEvents_EventType" CHECK ( "EventType" IN ('CREADO', 'PROGRAMADO', 'REPROGRAMADO', 'EN_ATENCION', 'SEGUIMIENTO', 'RESUELTO', 'ASIGNADO', 'REASIGNADO', 'SOLICITUD_RESOLUCION', 'SOLICITUD_CANCELACION', 'RESOLUCION_APROBADA', 'RESOLUCION_RECHAZADA', 'CANCELACION_APROBADA', 'CANCELACION_RECHAZADA', 'CANCELADO'));
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "CK_TicketEvents_Evidence" CHECK ("EvidenceId" IS NULL OR "EventType" IN ('CREADO','SEGUIMIENTO'));
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "CK_TicketEvents_Schedule" CHECK ((((("EventType")::text = 'PROGRAMADO'::text) AND ("PreviousScheduledAt" IS NULL) AND ("ScheduledAt" IS NOT NULL)) OR ((("EventType")::text = 'REPROGRAMADO'::text) AND ("PreviousScheduledAt" IS NOT NULL) AND ("ScheduledAt" IS NOT NULL) AND ("PreviousScheduledAt" <> "ScheduledAt")) OR ((("EventType")::text <> ALL (ARRAY[('PROGRAMADO'::character varying)::text, ('REPROGRAMADO'::character varying)::text])) AND ("PreviousScheduledAt" IS NULL) AND ("ScheduledAt" IS NULL))));
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "CK_TicketStatusRequests_Reason" CHECK ("Type" <> 'SOLICITUD_CANCELACION' OR ("Reason" IS NOT NULL AND length(btrim("Reason")) > 0));
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "CK_TicketStatusRequests_Review" CHECK ( ("Status"='PENDIENTE' AND "ReviewedByUserId" IS NULL AND "ReviewedAt" IS NULL) OR ("Status" IN ('APROBADA','RECHAZADA') AND "ReviewedByUserId" IS NOT NULL AND "ReviewedAt" IS NOT NULL));
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "CK_TicketStatusRequests_Status" CHECK ("Status" IN ('PENDIENTE','APROBADA','RECHAZADA'));
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "CK_TicketStatusRequests_Type" CHECK ("Type" IN ('SOLICITUD_RESOLUCION','SOLICITUD_CANCELACION'));
ALTER TABLE public."Tickets" ADD CONSTRAINT "CK_Tickets_Dates" CHECK ("UpdatedAt" >= "CreatedAt");
ALTER TABLE public."Tickets" ADD CONSTRAINT "CK_Tickets_Status" CHECK ("Status" IN ('Pending', 'InProgress', 'Resolved', 'Cancelled'));
ALTER TABLE public."Users" ADD CONSTRAINT "CK_Users_IsActive" CHECK ("IsActive" IN (0, 1));
ALTER TABLE public."CoordinatorTechnicians" ADD CONSTRAINT "CoordinatorTechnicians_CoordinatorUserId_fkey" FOREIGN KEY ("CoordinatorUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT;
ALTER TABLE public."CoordinatorTechnicians" ADD CONSTRAINT "CoordinatorTechnicians_TechnicianUserId_fkey" FOREIGN KEY ("TechnicianUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT;
ALTER TABLE public."Evidences" ADD CONSTRAINT "Evidences_TicketId_fkey" FOREIGN KEY ("TicketId") REFERENCES "Tickets"("Id") ON DELETE RESTRICT;
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "FK_TicketEvents_Evidences" FOREIGN KEY ("TicketId", "EvidenceId") REFERENCES "Evidences"("TicketId", "Id") ON DELETE RESTRICT;
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "TicketEvents_TicketId_fkey" FOREIGN KEY ("TicketId") REFERENCES "Tickets"("Id") ON DELETE RESTRICT;
ALTER TABLE public."TicketEvents" ADD CONSTRAINT "TicketEvents_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE RESTRICT;
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "TicketStatusRequests_RequesterUserId_fkey" FOREIGN KEY ("RequesterUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT;
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "TicketStatusRequests_ReviewedByUserId_fkey" FOREIGN KEY ("ReviewedByUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT;
ALTER TABLE public."TicketStatusRequests" ADD CONSTRAINT "TicketStatusRequests_TicketId_fkey" FOREIGN KEY ("TicketId") REFERENCES "Tickets"("Id") ON DELETE RESTRICT;
ALTER TABLE public."Tickets" ADD CONSTRAINT "Tickets_BranchId_fkey" FOREIGN KEY ("BranchId") REFERENCES "Branches"("Id") ON DELETE RESTRICT;
ALTER TABLE public."Tickets" ADD CONSTRAINT "Tickets_ReporterUserId_fkey" FOREIGN KEY ("ReporterUserId") REFERENCES "Users"("Id") ON DELETE RESTRICT;
ALTER TABLE public."Tickets" ADD CONSTRAINT "Tickets_TechnicianId_fkey" FOREIGN KEY ("TechnicianId") REFERENCES "Users"("Id") ON DELETE RESTRICT;
ALTER TABLE public."Users" ADD CONSTRAINT "FK_Users_Roles" FOREIGN KEY ("RoleId") REFERENCES "Roles"("Id") ON DELETE RESTRICT;

CREATE INDEX "IX_CoordinatorTechnicians_TechnicianUserId" ON public."CoordinatorTechnicians" USING btree ("TechnicianUserId");
CREATE INDEX "IX_Evidences_TicketId" ON public."Evidences" USING btree ("TicketId");
CREATE INDEX "IX_TicketEvents_TicketId_CreatedAt_Id" ON public."TicketEvents" USING btree ("TicketId", "CreatedAt", "Id");
CREATE INDEX "IX_TicketStatusRequests_Status_CreatedAt" ON public."TicketStatusRequests" USING btree ("Status", "CreatedAt", "Id");
CREATE INDEX "IX_TicketStatusRequests_TicketId" ON public."TicketStatusRequests" USING btree ("TicketId");
CREATE INDEX "IX_Tickets_BranchId" ON public."Tickets" USING btree ("BranchId");
CREATE INDEX "IX_Tickets_ReporterUserId" ON public."Tickets" USING btree ("ReporterUserId");
CREATE INDEX "IX_Tickets_TechnicianId_Status" ON public."Tickets" USING btree ("TechnicianId", "Status");

COMMIT;

-- Excluye usuarios inactivos; PasswordHash es exclusivamente interno.
CREATE OR REPLACE FUNCTION public.get_user_by_username(p_username character varying)
 RETURNS TABLE("Id" integer, "Username" character varying, "PasswordHash" text, "Name" character varying)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT u."Id", u."Username", u."PasswordHash", u."Name"
    FROM public."Users" AS u
    WHERE u."Username" = p_username AND u."IsActive" = 1;
$function$;

CREATE OR REPLACE VIEW public.agenda_tickets AS
 SELECT t."Id",
    t."BranchId",
    t."TechnicianId",
    t."Title",
    t."Description",
    t."Status",
    t."CreatedAt",
    t."UpdatedAt",
    t."ScheduledAt",
    t."ClientRequestId",
    b."Name" AS "BranchName",
    b."Address" AS "BranchAddress"
   FROM ("Tickets" t
     JOIN "Branches" b ON ((b."Id" = t."BranchId")));

-- Esta versión no requiere triggers.

-- Datos exclusivamente DEMO; no instalar en producción.
-- DEMO: **tecnico1 / Demo123***.
-- DEMO: **admin1 / AdminDemo123***.
-- DEMO: **coordinador1 / Demo123***.
-- DEMO: **usuario1 / Demo123***.
BEGIN;
INSERT INTO public."Roles" ("Id","Name") VALUES (1,'Administrador'),(2,'Técnico'),(3,'Coordinador'),(4,'Usuario') ON CONFLICT ("Id") DO NOTHING;
INSERT INTO public."Users" ("Username","PasswordHash","Name","RoleId","IsActive") VALUES ('tecnico1','AQAAAAIAAYagAAAAECG6+xJ1OmiicKseDoLWq//XHERs/rdTMrsLDXb0cG0M1yctPgH/ccHy5f0oMZfJOw==','Técnico Demo',2,1) ON CONFLICT ("Username") DO NOTHING;
INSERT INTO public."Users" ("Username","PasswordHash","Name","RoleId","IsActive") VALUES ('admin1','AQAAAAIAAYagAAAAEPeyUp5aPa5HMUJF63XNzJg6pTjdPAUNbC6T+QFbvR+ZZEBAW+TAJvumKNRSkWKO8Q==','Administrador Demo',1,1) ON CONFLICT ("Username") DO NOTHING;
INSERT INTO public."Users" ("Username","PasswordHash","Name","RoleId","IsActive") VALUES ('coordinador1','AQAAAAIAAYagAAAAEOta4mF6bd6171x0kNvQDdv1IPpQLEvPQtsMNeEOV8pwT2FXiYxnx/9JnW47DZgvKA==','Coordinador Demo',3,1) ON CONFLICT ("Username") DO NOTHING;
INSERT INTO public."Users" ("Username","PasswordHash","Name","RoleId","IsActive") VALUES ('usuario1','AQAAAAIAAYagAAAAEOeDSYFHkV03LJfqaJbnl7QgLUWNGjnUqn9YgxEynuoGTJ5eZCYyIMjeJyrsWEASag==','Usuario Demo',4,1) ON CONFLICT ("Username") DO NOTHING;
INSERT INTO public."CoordinatorTechnicians" ("CoordinatorUserId","TechnicianUserId") SELECT c."Id",t."Id" FROM public."Users" c CROSS JOIN public."Users" t WHERE c."Username"='coordinador1' AND t."Username"='tecnico1' ON CONFLICT DO NOTHING;
INSERT INTO public."Branches" ("Name","Address") SELECT 'Sucursal Demo Centro','Calle Demo 10, Centro' WHERE NOT EXISTS (SELECT 1 FROM public."Branches" WHERE "Name"='Sucursal Demo Centro' AND "Address"='Calle Demo 10, Centro');
INSERT INTO public."Tickets" ("BranchId","TechnicianId","ReporterUserId","Title","Description","Status","CreatedAt","UpdatedAt","ScheduledAt","ClientRequestId") SELECT b."Id",t."Id",u."Id",'Demo: revisión de equipo','El equipo no inicia.','Pending',TIMESTAMPTZ '2026-10-01 10:00:00+00',TIMESTAMPTZ '2026-10-01 10:30:00+00',TIMESTAMPTZ '2026-10-01 15:00:00+00','10000000-0000-4000-8000-000000000001' FROM public."Branches" b CROSS JOIN public."Users" t CROSS JOIN public."Users" u WHERE b."Name"='Sucursal Demo Centro' AND b."Address"='Calle Demo 10, Centro' AND t."Username"='tecnico1' AND u."Username"='usuario1' ON CONFLICT ("ClientRequestId") DO NOTHING;
INSERT INTO public."Tickets" ("BranchId","TechnicianId","ReporterUserId","Title","Description","Status","CreatedAt","UpdatedAt","ScheduledAt","ClientRequestId") SELECT b."Id",t."Id",u."Id",'Demo: diagnóstico en curso','La conexión es intermitente.','InProgress',TIMESTAMPTZ '2026-10-01 10:00:00+00',TIMESTAMPTZ '2026-10-01 10:30:00+00',TIMESTAMPTZ '2026-10-01 15:00:00+00','10000000-0000-4000-8000-000000000002' FROM public."Branches" b CROSS JOIN public."Users" t CROSS JOIN public."Users" u WHERE b."Name"='Sucursal Demo Centro' AND b."Address"='Calle Demo 10, Centro' AND t."Username"='tecnico1' AND u."Username"='usuario1' ON CONFLICT ("ClientRequestId") DO NOTHING;
INSERT INTO public."Tickets" ("BranchId","TechnicianId","ReporterUserId","Title","Description","Status","CreatedAt","UpdatedAt","ScheduledAt","ClientRequestId") SELECT b."Id",NULL,u."Id",'Demo: reporte sin asignar','Solicitud nueva pendiente de programación.','Pending',TIMESTAMPTZ '2026-10-01 10:00:00+00',TIMESTAMPTZ '2026-10-01 10:30:00+00',NULL,'10000000-0000-4000-8000-000000000003' FROM public."Branches" b CROSS JOIN public."Users" t CROSS JOIN public."Users" u WHERE b."Name"='Sucursal Demo Centro' AND b."Address"='Calle Demo 10, Centro' AND t."Username"='tecnico1' AND u."Username"='usuario1' ON CONFLICT ("ClientRequestId") DO NOTHING;
INSERT INTO public."Evidences" ("TicketId","Description","CreatedAt") SELECT "Id",'Demo: cableado revisado.',TIMESTAMPTZ '2026-10-01 10:30:00+00' FROM public."Tickets" t WHERE "ClientRequestId"='10000000-0000-4000-8000-000000000002' AND NOT EXISTS (SELECT 1 FROM public."Evidences" WHERE "TicketId"=t."Id" AND "Description"='Demo: cableado revisado.');
INSERT INTO public."TicketEvents" ("TicketId","EventType","Description","CreatedAt","UserId","ClientRequestId","ScheduledAt","EvidenceId") SELECT t."Id",'CREADO','Ticket demo registrado.',TIMESTAMPTZ '2026-10-01 10:00:00+00',u."Id",'20000000-0000-4000-8000-000000000001',NULL,NULL FROM public."Tickets" t CROSS JOIN public."Users" u WHERE t."ClientRequestId"='10000000-0000-4000-8000-000000000001' AND u."Username"='usuario1' ON CONFLICT ("UserId","ClientRequestId") DO NOTHING;
INSERT INTO public."TicketEvents" ("TicketId","EventType","Description","CreatedAt","UserId","ClientRequestId","ScheduledAt","EvidenceId") SELECT t."Id",'PROGRAMADO','Atención demo programada.',TIMESTAMPTZ '2026-10-01 10:05:00+00',u."Id",'30000000-0000-4000-8000-000000000001',TIMESTAMPTZ '2026-10-01 15:00:00+00',NULL FROM public."Tickets" t CROSS JOIN public."Users" u WHERE t."ClientRequestId"='10000000-0000-4000-8000-000000000001' AND u."Username"='coordinador1' ON CONFLICT ("UserId","ClientRequestId") DO NOTHING;
INSERT INTO public."TicketEvents" ("TicketId","EventType","Description","CreatedAt","UserId","ClientRequestId","ScheduledAt","EvidenceId") SELECT t."Id",'CREADO','Ticket demo registrado.',TIMESTAMPTZ '2026-10-01 10:00:00+00',u."Id",'20000000-0000-4000-8000-000000000002',NULL,NULL FROM public."Tickets" t CROSS JOIN public."Users" u WHERE t."ClientRequestId"='10000000-0000-4000-8000-000000000002' AND u."Username"='usuario1' ON CONFLICT ("UserId","ClientRequestId") DO NOTHING;
INSERT INTO public."TicketEvents" ("TicketId","EventType","Description","CreatedAt","UserId","ClientRequestId","ScheduledAt","EvidenceId") SELECT t."Id",'PROGRAMADO','Atención demo programada.',TIMESTAMPTZ '2026-10-01 10:05:00+00',u."Id",'30000000-0000-4000-8000-000000000002',TIMESTAMPTZ '2026-10-01 15:00:00+00',NULL FROM public."Tickets" t CROSS JOIN public."Users" u WHERE t."ClientRequestId"='10000000-0000-4000-8000-000000000002' AND u."Username"='coordinador1' ON CONFLICT ("UserId","ClientRequestId") DO NOTHING;
INSERT INTO public."TicketEvents" ("TicketId","EventType","Description","CreatedAt","UserId","ClientRequestId","ScheduledAt","EvidenceId") SELECT t."Id",'CREADO','Ticket demo registrado.',TIMESTAMPTZ '2026-10-01 10:00:00+00',u."Id",'20000000-0000-4000-8000-000000000003',NULL,NULL FROM public."Tickets" t CROSS JOIN public."Users" u WHERE t."ClientRequestId"='10000000-0000-4000-8000-000000000003' AND u."Username"='usuario1' ON CONFLICT ("UserId","ClientRequestId") DO NOTHING;
INSERT INTO public."TicketEvents" ("TicketId","EventType","Description","CreatedAt","UserId","ClientRequestId","ScheduledAt","EvidenceId") SELECT t."Id",'EN_ATENCION','Atención demo iniciada.',TIMESTAMPTZ '2026-10-01 10:10:00+00',u."Id",'40000000-0000-4000-8000-000000000001',NULL,NULL FROM public."Tickets" t CROSS JOIN public."Users" u WHERE t."ClientRequestId"='10000000-0000-4000-8000-000000000002' AND u."Username"='tecnico1' ON CONFLICT ("UserId","ClientRequestId") DO NOTHING;
INSERT INTO public."TicketEvents" ("TicketId","EventType","Description","CreatedAt","UserId","ClientRequestId","ScheduledAt","EvidenceId") SELECT t."Id",'SEGUIMIENTO','Demo: cableado revisado.',TIMESTAMPTZ '2026-10-01 10:30:00+00',u."Id",'40000000-0000-4000-8000-000000000002',NULL,(SELECT MIN(e."Id") FROM public."Evidences" e WHERE e."TicketId"=t."Id" AND e."Description"='Demo: cableado revisado.') FROM public."Tickets" t CROSS JOIN public."Users" u WHERE t."ClientRequestId"='10000000-0000-4000-8000-000000000002' AND u."Username"='tecnico1' ON CONFLICT ("UserId","ClientRequestId") DO NOTHING;
COMMIT;
