<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Ajustar IdentificadorAlmacenSecrets para seleccionar otro almacén local.
         ASP.NET Core lo carga en Development; las claves internas se seleccionan
         mediante SecretsApi en appsettings.json, sin cambiar código. -->
    <IdentificadorAlmacenSecrets>ce8894f4-5c74-441b-a964-b601e9520a3c</IdentificadorAlmacenSecrets>
    <UserSecretsId>$(IdentificadorAlmacenSecrets)</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>


</Project>
